=== bekondo84/Teratech/Teratech_tools/megatim-tools/src/main/resources/model-config.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"
           targetNamespace="http://www.megatimgroup.net/model-config"
           xmlns:tns="http://www.megatimgroup.net/model-config"
           elementFormDefault="qualified">


    <xs:element name="model-config">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="tns:elements" minOccurs="1" maxOccurs="1" />
            </xs:sequence>
        </xs:complexType>
    </xs:element>

    <xs:element name="elements">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="tns:element" minOccurs="0" maxOccurs="unbounded" />
            </xs:sequence>
        </xs:complexType>
    </xs:element>

    <xs:element name="element">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="tns:roles" minOccurs="1" maxOccurs="1" />
                <xs:element ref="tns:exclures" minOccurs="1" maxOccurs="1" />
                <xs:element ref="tns:groupes" minOccurs="1" maxOccurs="1" />
                <xs:element ref="tns:relations" minOccurs="1" maxOccurs="1" />
            </xs:sequence>
            <xs:attribute name="type" type="xs:string" use="required" />
            <xs:attribute name="validate_type" type="xs:string" use="optional" default=""/>
            <xs:attribute name="reject_type" type="xs:string" use="optional" default=""/>
            <xs:attribute name="idclass" type="xs:string" use="required" />
            <xs:attribute name="idname" type="xs:string" use="required" />
            <xs:attribute name="internal" type="xs:boolean" use="required" />
            <xs:attribute name="test" type="xs:boolean" use="optional" default="false"/>
            <xs:attribute name="deseable" type="xs:boolean" use="optional" default="false" />
            <xs:attribute name="reporting" type="xs:boolean" use="optional" default="false" />
            <xs:attribute name="prefix" type="xs:string" use="optional" default="" />
        </xs:complexType>
    </xs:element>

    <xs:element name="relations">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="tns:one-to-many" minOccurs="0" maxOccurs="unbounded" />
                <xs:element ref="tns:one-to-one" minOccurs="0" maxOccurs="unbounded" />
                <xs:element ref="tns:many-to-many" minOccurs="0" maxOccurs="unbounded" />     
                <!-- <xs:element ref="tns:many-to-one" minOccurs="0" maxOccurs="unbounded" />   -->                             
            </xs:sequence>			
        </xs:complexType>
    </xs:element>
        
    <xs:element name="exclures">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="tns:exclure" minOccurs="0" maxOccurs="unbounded" />
            </xs:sequence>			
        </xs:complexType>
    </xs:element>
        
    <xs:element name="groupes">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="tns:groupe" minOccurs="0" maxOccurs="unbounded" />
            </xs:sequence>			
        </xs:complexType>
    </xs:element>
        
    <xs:element name="roles">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="tns:role" minOccurs="0" maxOccurs="unbounded" />
            </xs:sequence>			
        </xs:complexType>
    </xs:element>

    <xs:element name="role"  >
        <xs:complexType>
            <xs:sequence>
                <xs:element name="role" type="xs:string" />
            </xs:sequence>			
        </xs:complexType>
    </xs:element>
        
    <xs:element name="one-to-many"  >
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="tns:summary" minOccurs="0" maxOccurs="1" />
            </xs:sequence>                    
            <xs:attribute name="name" type="xs:string" use="required" />	
            <xs:attribute name="cascade" type="xs:string" use="optional" default="all"  />                                            	
        </xs:complexType>
    </xs:element>
        
    <xs:element name="many-to-many"  >
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="tns:summary" minOccurs="0" maxOccurs="1" />
            </xs:sequence> 
            <xs:attribute name="name" type="xs:string" use="required" />                                                                  	
        </xs:complexType>
    </xs:element>
        
    <xs:element name="one-to-one"  >
        <xs:complexType>
            <xs:attribute name="name" type="xs:string" use="required" />     
            <xs:attribute name="cascade" type="xs:string" use="optional" default="all"  />                                                                	
        </xs:complexType>
    </xs:element>
        
    <xs:element name="summary"  >
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="tns:column" minOccurs="1" maxOccurs="unbounded" />
            </xs:sequence>                      	
        </xs:complexType>
    </xs:element>
        
    <xs:element name="column"  >
        <xs:complexType>
            <xs:attribute name="value" type="xs:string" use="required" />                       	
        </xs:complexType>
    </xs:element>
        
    <xs:element name="exclure"  >
        <xs:complexType>
            <xs:attribute name="name" type="xs:string" use="required" />	
            <xs:attribute name="all" type="xs:boolean" use="optional" default="false" />
            <xs:attribute name="edit" type="xs:boolean" use="optional" default="false" />
            <xs:attribute name="search" type="xs:boolean" use="optional" default="true" />
            <xs:attribute name="model" type="xs:boolean" use="optional" default="true" />		
        </xs:complexType>
    </xs:element>
        
    <xs:element name="groupe"  >
        <xs:complexType>
            <xs:attribute name="name" type="xs:string" use="required" />
            <xs:attribute name="label" type="xs:string" use="required" />	
            <xs:attribute name="indexs" type="xs:string" use="required" />		
        </xs:complexType>
    </xs:element>

    <xs:element name="frame-config">            
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="tns:principalscreen" minOccurs="1" maxOccurs="1" />
            </xs:sequence>
        </xs:complexType>
    </xs:element>
    <xs:element name="principalscreen">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="tns:module" minOccurs="0" maxOccurs="unbounded" />
            </xs:sequence>
            <xs:attribute name="name" type="xs:string" use="required" />
        </xs:complexType>
    </xs:element>
    <xs:element name="module">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="tns:action" minOccurs="0" maxOccurs="unbounded" />
                <xs:element ref="tns:submodule" minOccurs="0" maxOccurs="unbounded" />
            </xs:sequence>
            <xs:attribute name="name" type="xs:string" use="required" />    
            <xs:attribute name="label" type="xs:string" use="required" /> 
            <xs:attribute name="vmenu" type="xs:boolean" use="optional" default="true"/>                                   
        </xs:complexType>
    </xs:element>
    <xs:element name="submodule">
        <xs:complexType>
            <xs:sequence>   
                <xs:element ref="tns:action" minOccurs="0" maxOccurs="unbounded" />                
            </xs:sequence>
            <xs:attribute name="name" type="xs:string" use="required" />    
            <xs:attribute name="label" type="xs:string" use="required" />   
            <xs:attribute name="independent" type="xs:boolean" default="false" />            
        </xs:complexType>            
    </xs:element>   
    <xs:element name="action">
        <xs:complexType>
            <xs:attribute name="label" type="xs:string" use="required" />
            <xs:attribute name="classname" type="xs:string" use="required" />  
            <xs:attribute name="actionname" type="xs:string" use="required" />   
            <xs:attribute name="actionindex" type="xs:int" use="required" /> 
            <xs:attribute name="mnemonic" type="xs:string" use="required" />   
            <xs:attribute name="prefix" type="xs:string" use="optional" default="" /> 
            <xs:attribute name="separator" type="xs:boolean"  default="false" />   
            <xs:attribute name="literal" type="xs:boolean"  default="false" />
            <xs:attribute name="dialog" type="xs:boolean"  default="false" />                           
        </xs:complexType>
    </xs:element>
    
    <xs:element name="temporalfile">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="tns:fileline" minOccurs="0" maxOccurs="unbounded" />
            </xs:sequence>           
        </xs:complexType>
    </xs:element>
     <xs:element name="fileline">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="tns:linecolumn" minOccurs="0" maxOccurs="unbounded" />               
            </xs:sequence>                                         
        </xs:complexType>
    </xs:element>
    <xs:element name="linecolumn">
        <xs:complexType>
            <xs:attribute name="name" type="xs:string" use="required" />
            <xs:attribute name="value" type="xs:string" use="required" /> 
            <xs:attribute name="type" type="xs:int" use="required" />   
            <xs:attribute name="row" type="xs:int" use="required" />     
            <xs:attribute name="column" type="xs:int" use="required" />                           
        </xs:complexType>
    </xs:element>
</xs:schema>

=== bekondo84/Teratech/keren-erp/core-model/src/main/resources/model.xml
<?xml version="1.0"?>
<!--
To change this license header, choose License Headers in Project Properties.
To change this template file, choose Tools | Templates
and open the template in the editor.
-->

<model-config xmlns:xsi="http://www.w3.org/2001/XMLSchema"
	xsi:schemaLocation="http://www.megatimgroup.net/model-config ../xsd/model-config.xsd"
	xmlns="http://www.megatimgroup.net/model-config">
    <elements>
<!--        <element type="com.core.model.server.Etudiant"  idclass="long"  idname="id"   deseable="false">
            <roles>
                <role>ADMIN</role>
            </roles>           
        </element>        -->
        <element type="com.core.menus.MenuModule"  idclass="long"  idname="id" deseable="true">
            <roles>
                <role>ADMIN</role>
            </roles>           
        </element>
        <element type="com.core.menus.MenuGroupActions"  idclass="long"  idname="id" deseable="true">
            <roles>
                <role>ADMIN</role>
            </roles>           
        </element>
        <element type="com.core.menus.MenuAction"  idclass="long"  idname="id" deseable="true">
            <roles>
                <role>ADMIN</role>
            </roles>           
        </element>
        <element type="com.core.menus.ActionItem"  idclass="long"  idname="id" deseable="true">
            <roles>
                <role>ADMIN</role>
            </roles>           
        </element>   
        <element type="com.core.referentiels.Societe"  idclass="Long"  idname="id"  deseable="true">
            <roles>
                <role>ADMIN</role>
            </roles>           
        </element>   
        <element type="com.core.referentiels.Pays"  idclass="Long"  idname="id"   deseable="true">
            <roles>
                <role>ADMIN</role>
            </roles>           
        </element>  
        <element type="com.core.langues.Langue"  idclass="Long"  idname="id"   deseable="true">
            <roles>
                <role>ADMIN</role>
            </roles>           
        </element>  
        <element type="com.core.langues.ChargerLangue"  idclass="Long"  idname="id"   deseable="true">
            <roles>
                <role>ADMIN</role>
            </roles>           
        </element>
        <element type="com.core.securites.Groupe"  idclass="Long"  idname="id"   deseable="true">
            <roles>
                <role>ADMIN</role>
            </roles>           
        </element>  
        <element type="com.core.referentiels.Devise"  idclass="Long"  idname="id"   deseable="true">
            <roles>
                <role>ADMIN</role>
            </roles>           
        </element>  
        <element type="com.core.securites.Utilisateur"  idclass="Long"  idname="id"   deseable="true">
            <roles>
                <role>ADMIN</role>
            </roles>           
        </element> 
        <element type="com.core.calendar.Event"  idclass="Long"  idname="id"   deseable="true">
            <roles>
                <role>ADMIN</role>
            </roles>           
        </element> 
        <element type="com.core.calendar.Rappel"  idclass="Long"  idname="id"   deseable="true">
            <roles>
                <role>ADMIN</role>
            </roles>           
        </element>  
        <element type="com.core.views.FormRecord"  idclass="Long"  idname="id"   deseable="true">
            <roles>
                <role>ADMIN</role>
            </roles>           
        </element>
        <element type="com.core.views.TreeRecord"  idclass="Long"  idname="id"   deseable="true">
            <roles>
                <role>ADMIN</role>
            </roles>           
        </element>
        <element type="com.core.views.ReportRecord"  idclass="Long"  idname="id"   deseable="true">
            <roles>
                <role>ADMIN</role>
            </roles>           
        </element>
        <element type="com.core.referentiels.PieceJointe"  idclass="Long"  idname="id"   deseable="true">
            <roles>
                <role>ADMIN</role>
            </roles>           
        </element>
        <element type="com.core.views.DashboardRecord"  idclass="Long"  idname="id"   deseable="true">
            <roles>
                <role>ADMIN</role>
            </roles>           
        </element>
        <element type="com.core.discussions.Canal"  idclass="Long"  idname="id"   deseable="true">
            <roles>
                <role>ADMIN</role>
            </roles>           
        </element>
        <element type="com.core.discussions.SMessage"  idclass="Long"  idname="id"   deseable="true">
            <roles>
                <role>ADMIN</role>
            </roles>           
        </element>
        <element type="com.core.discussions.RMessage"  idclass="Long"  idname="id"   deseable="true">
            <roles>
                <role>ADMIN</role>
            </roles>           
        </element>
        <element type="com.core.discussions.KMessage"  idclass="Long"  idname="id"   deseable="true">
            <roles>
                <role>ADMIN</role>
            </roles>           
        </element>
        <element type="com.core.discussions.Follower"  idclass="Long"  idname="id"   deseable="true">
            <roles>
                <role>ADMIN</role>
            </roles>           
        </element>
        <element type="com.core.views.CalendarRecord"  idclass="Long"  idname="id"   deseable="true">
            <roles>
                <role>ADMIN</role>
            </roles>           
        </element>
   </elements>
    
</model-config>

=== bekondo84/Teratech/stocks/stock-model/src/main/resources/model.xml
<?xml version="1.0"?>
<!--
To change this license header, choose License Headers in Project Properties.
To change this template file, choose Tools | Templates
and open the template in the editor.
-->

<model-config xmlns:xsi="http://www.w3.org/2001/XMLSchema"
	xsi:schemaLocation="http://www.megatimgroup.net/model-config ../xsd/model-config.xsd"
	xmlns="http://www.megatimgroup.net/model-config">
    <elements>
        <element type="com.teratech.stock.model.base.FamilleArticle"  idclass="long"  idname="id"   deseable="true">
            <roles>
                <role>ADMIN</role>
            </roles>           
        </element>        
        <element type="com.teratech.stock.model.base.Article"  idclass="long"  idname="id" deseable="true">
            <roles>
                <role>ADMIN</role>
            </roles>           
        </element>
       <element type="com.teratech.stock.model.base.CategorieProduit"  idclass="long"  idname="id" deseable="true">
            <roles>
                <role>ADMIN</role>
            </roles>           
        </element>
        <element type="com.teratech.stock.model.base.Pays"  idclass="long"  idname="id" deseable="true">
            <roles>
                <role>ADMIN</role>
            </roles>           
        </element>   
        <element type="com.teratech.stock.model.base.UniteAchat"  idclass="long"  idname="id" deseable="true">
            <roles>
                <role>ADMIN</role>
            </roles>           
        </element>   
        <element type="com.teratech.stock.model.base.UniteGestion"  idclass="long"  idname="id" deseable="true">
            <roles>
                <role>ADMIN</role>
            </roles>           
        </element>   
        <element type="com.teratech.stock.model.comptabilite.JournalComptable"  idclass="Long"  idname="id"  deseable="true">
            <roles>
                <role>ADMIN</role>
            </roles>           
        </element>   
        <element type="com.teratech.stock.model.comptabilite.Compte"  idclass="Long"  idname="id"   deseable="true">
            <roles>
                <role>ADMIN</role>
            </roles>           
        </element>  
        <element type="com.teratech.stock.model.comptabilite.CompteAnalytique"  idclass="Long"  idname="id"   deseable="true">
            <roles>
                <role>ADMIN</role>
            </roles>           
        </element>  
        <element type="com.teratech.stock.model.comptabilite.NiveauAnalyse"  idclass="Long"  idname="id"   deseable="true">
            <roles>
                <role>ADMIN</role>
            </roles>           
        </element>
        <element type="com.teratech.stock.model.comptabilite.SectionAnalytique"  idclass="Long"  idname="id"   deseable="true">
            <roles>
                <role>ADMIN</role>
            </roles>           
        </element>  
        <element type="com.teratech.stock.model.comptabilite.Taxe"  idclass="Long"  idname="id"   deseable="true">
            <roles>
                <role>ADMIN</role>
            </roles>           
        </element>  
        <element type="com.teratech.stock.model.base.Entrepot"  idclass="Long"  idname="id"   deseable="true">
            <roles>
                <role>ADMIN</role>
            </roles>           
        </element>
        <element type="com.teratech.stock.model.base.Region"  idclass="Long"  idname="id"   deseable="true">
            <roles>
                <role>ADMIN</role>
            </roles>           
        </element> 
        <element type="com.teratech.stock.model.base.Region"  idclass="Long"  idname="id"   deseable="true">
            <roles>
                <role>ADMIN</role>
            </roles>           
        </element> 
       <element type="com.teratech.stock.model.base.Tier"  idclass="Long"  idname="id"   deseable="true">
            <roles>
                <role>ADMIN</role>
            </roles>           
        </element> 
        <element type="com.teratech.stock.model.base.Civilite"  idclass="Long"  idname="id"   deseable="true">
            <roles>
                <role>ADMIN</role>
            </roles>           
        </element>  
        <element type="com.teratech.stock.model.base.Contact"  idclass="Long"  idname="id"   deseable="true">
            <roles>
                <role>ADMIN</role>
            </roles>           
        </element>
        <element type="com.teratech.stock.model.base.Entrepot"  idclass="Long"  idname="id"   deseable="true">
            <roles>
                <role>ADMIN</role>
            </roles>           
        </element>
         <element type="com.teratech.stock.model.banques.Banque"  idclass="Long"  idname="id"   deseable="true">
            <roles>
                <role>ADMIN</role>
            </roles>           
        </element>
        <element type="com.teratech.stock.model.banques.CompteBancaire"  idclass="Long"  idname="id"   deseable="true">
            <roles>
                <role>ADMIN</role>
            </roles>           
        </element>
        <element type="com.teratech.stock.model.base.Devise"  idclass="Long"  idname="id"   deseable="true">
            <roles>
                <role>ADMIN</role>
            </roles>           
        </element>
        <element type="com.teratech.stock.model.base.Societe"  idclass="Long"  idname="id"   deseable="true">
            <roles>
                <role>ADMIN</role>
            </roles>           
        </element>
   </elements>    
</model-config>
